# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('text', models.TextField(max_length=1000)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
